package com.example.utils

const val API_ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjZmM4Y2U3Y2RhNjZiZmU5NzkxMGE3MTYxZTZiNWY4YSIsIm5iZiI6MTczMTczNTIyNS40NjYyNDU3LCJzdWIiOiI2NzM4Mjg2ZGFkMjc4YTg5NjNmODMzZjMiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.TOD8VYYgOiaim_VvI2sShiuzDf2ggfpF_oG3SWDyGOU"
const val BASE_URL = "https://api.themoviedb.org/3/"
const val ENDPOINT_SEARCH = "search/multi"